---
rules:
  comments:
    min-spaces-from-content: 1 # Changed this to stop a mess between linters from Prettier (vscode) to yamllint - https://github.com/prettier/prettier/pull/10926 / https://github.com/redhat-developer/vscode-yaml/issues/433#issuecomment-2276330837
